### ISSUE TITLE
qiankun微前端踩坑

### ISSUE THREAD

**Issue by bowencool** [bowencool/blog#9]
# 技术坑

##### 现象

子应用跳主应用路由，主应用路由无反应，router-view 不更新，popstate 事件不触发，路由守卫全失效。

> 原生 pushState 确实不会触发 popstate 事件

##### 临时方案：

- 在子应用：
  - 劫持 push/replace 方法，通知主应用。这样等于是侵入式代码，耦合严重，一点都不优雅。
- 在主应用：
  - 监听路由事件，判断目标路径。也有点蠢，但是这样可以做到子应用无感知，后期优化方便。

```flow
event=>start: 路由事件
resolve=>condition: 是主应用的页面吗
child=>operation: next()
parent=>operation: replaceState/forceUpdate

event->resolve
resolve(yes)->parent
resolve(no)->child
```

##### 事后找到原因：

single-spa 劫持了 addEventListner 等一系列原生 API，导致 vue-router 的 popstate 处理函数无法执行。解决方案是**调整加载顺序**

### 子应用 HMR 热更新失效

解决方案同上

### 沙箱问题

子应用对全局对象的修改没有限制，只是记录了快照，卸载时恢复。因此产生的问题有：

- 把主应用的全局变量都污染了，(通过 external 的方式加载时)无法处理多版本共存、多应用共存。还好暂时没这种需求
- [#578](https://github.com/umijs/qiankun/issues/578#issuecomment-629137733)

官方后续考虑[迁移](https://github.com/umijs/qiankun/blob/master/src/sandbox/legacy/sandbox.ts#L24)

### 升级乾坤自带 bug

暂时锁版本呗

# 业务坑

### ~~菜单权限问题~~

~~推动服务端一起改造。~~

### 业务模块在平台之间的差异

- 人力抹平差异
- 增量式的重构，改到哪个模块/页面，就拆哪个。

### 隐形路由（不属于任何模块，也不在菜单显示）的跳转

人力排查、合并

# 工程问题

### 公共逻辑

- 抽到 npm
  - 业务组件库等
- 抽不动的通过 props 传进来
  - 比如接口请求方法，因为存在大量配置，而且平台之间不同，所以在子应用中做区分是非常冗余的
  - 这样也会导致一个问题：子应用没法单独运行，这个后期跟 lib(请求库) 一起优化

**Comment by ShiChenCong** [comment]
调整加载顺序 指的是什么顺序？

**Comment by bowencool** [comment]
> 调整加载顺序 指的是什么顺序？

``` diff
+ import { xxx } from 'qiankun'
  import router from './router'
- import { xxx } from 'qiankun'
```

**Comment by ShiChenCong** [comment]
我的好像不是同一个问题，我的问题是，子应用可以单独热更新，在主应用里，主应用监听子应用的变化，及时热更新
